metadata:
  name: unbound-deployment
  labels:
    app: unbound-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: futamint/unbound-gke:latest
        ports:
        - containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-loadbarancer
spec:
  selector:
    app: unbound
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
  type: LoadBalancer
